name: playground
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/static/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat/static/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Montserrat/static/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat/static/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/static/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Montserrat/static/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/static/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat/static/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat/static/Montserrat-Italic.ttf
          weight: 400
        - asset: fonts/Montserrat/static/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/static/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Montserrat/static/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/static/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
    - family: OpenSans
      fonts:
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Italic.ttf
          weight: 400
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic